# Generated by Django 3.2.9 on 2021-11-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacenes', '0001_initial'),
        ('movimientos', '0001_initial'),
        ('referencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('det_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('det_cantidad', models.CharField(max_length=100)),
                ('det_observacion', models.TextField(blank=True, max_length=200)),
                ('det_creado', models.DateField(auto_now_add=True)),
                ('det_modificado', models.DateField(auto_now=True)),
                ('alm_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacenes.almacen')),
                ('mov_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movimientos.movimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_mac', models.TextField(max_length=100)),
                ('reg_sn', models.TextField(max_length=100)),
                ('u_creado', models.DateField(auto_now_add=True)),
                ('u_modificado', models.DateField(auto_now=True)),
                ('det_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detalles.detalle')),
                ('ref_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referencias.referencia')),
            ],
        ),
    ]
