# Generated by Django 3.2.9 on 2021-12-03 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('usuario', models.OneToOneField(db_column='p_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('cargo', models.TextField(db_column='p_cargo', max_length=200)),
                ('creado', models.DateField(auto_now_add=True, db_column='p_creado')),
                ('modificado', models.DateField(auto_now=True, db_column='p_modificado')),
            ],
        ),
    ]
