# Generated by Django 3.2.9 on 2021-11-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('cargo', models.TextField(max_length=200)),
                ('u_creado', models.DateField(auto_now_add=True)),
                ('u_modificado', models.DateField(auto_now=True)),
            ],
        ),
    ]
