# Generated by Django 3.2.9 on 2021-11-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('ref_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('ref_marca', models.TextField(max_length=50)),
                ('ref_nombre', models.TextField(max_length=50)),
                ('ref_observacion', models.TextField(blank=True, max_length=200)),
                ('ref_creado', models.DateField(auto_now_add=True)),
                ('ref_modificado', models.DateField(auto_now=True)),
            ],
        ),
    ]
