# Generated by Django 3.2.9 on 2021-12-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.AutoField(db_column='r_codigo', primary_key=True, serialize=False)),
                ('marca', models.TextField(db_column='r_marca', max_length=50)),
                ('nombre', models.TextField(db_column='r_nombre', max_length=50)),
                ('observacion', models.TextField(blank=True, db_column='r_observacion', max_length=200)),
                ('creado', models.DateField(auto_now_add=True, db_column='r_creado')),
                ('modificado', models.DateField(auto_now=True, db_column='r_modificado')),
            ],
        ),
    ]
