# Generated by Django 3.2.9 on 2021-11-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('mov_codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mov_nombre', models.TextField(max_length=50)),
                ('mov_operador', models.CharField(max_length=5)),
                ('mov_tipo', models.CharField(choices=[('S', 'Suma'), ('R', 'Resta'), ('O', 'Opeara')], default='O', max_length=2)),
                ('mov_creado', models.DateField(auto_now_add=True)),
                ('mov_modificado', models.DateField(auto_now=True)),
            ],
        ),
    ]
