# Generated by Django 3.2.9 on 2021-11-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('alm_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('alm_nombre', models.TextField(max_length=50)),
                ('alm_direccion', models.TextField(max_length=100)),
                ('alm_creado', models.DateField(auto_now_add=True)),
                ('alm_modificado', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_cantidad', models.TextField(max_length=50)),
                ('inv_creado', models.DateField(auto_now_add=True)),
                ('inv_modificado', models.DateField(auto_now=True)),
                ('alm_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen')),
                ('ref_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referencias.referencia')),
            ],
        ),
        migrations.AddField(
            model_name='almacen',
            name='referencias',
            field=models.ManyToManyField(through='almacenes.Inventario', to='referencias.Referencia'),
        ),
    ]
