# Generated by Django 3.2.9 on 2021-12-04 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referencias', '0001_initial'),
        ('almacenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='almacen',
            field=models.ForeignKey(db_column='a_codigo', on_delete=django.db.models.deletion.CASCADE, to='almacenes.almacen', unique=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='referencia',
            field=models.ForeignKey(db_column='r_codigo', on_delete=django.db.models.deletion.CASCADE, to='referencias.referencia', unique=True),
        ),
    ]
