# Generated by Django 3.2.9 on 2021-12-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0002_auto_20211204_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.IntegerField(db_column='i_cantidad', default=0, unique=True),
        ),
    ]
